### PR TITLE
[WIP] tagging

### PR DESCRIPTION
**Pull request by DanCech**
This is a very basic first cut of tagging support in carbon, designed to be used in conjunction with https://github.com/DanCech/graphite-web/pull/1

It defines a format for tagged series in carbon, which is `<metric>;<tag1>=<value1>;<tag2>=<value2>`

This format was chosen to remain compatible with existing carbon-based tooling as much as possible, while maintaining a clear format for defining tags and avoiding any issues with tag names or values containing `.`, which is an issue for implementations that embed tag/value pairs as nodes within the dotted series name.

The major changes to the carbon pipeline are:

- use of TaggedSeries class (shared with graphite-web, could maybe be put into a separate library) to canonicalize tagged series names by ordering tags alphabetically by tag name immediately before putting the points into the write cache
- make HTTP POST to the new `/tags/tagSeries` endpoint in graphite-web to add series to the tag database, this currently happens on every create operation and on ~1% (this will likely need to be made configurable) of update operations

The biggest architecture change is that carbon now needs to be aware of the location of graphite-web (hence the new `GRAPHITE_URL` configuration item) so that it can make the HTTP calls to add series to the tag database.

The biggest issue with the current implementation in carbon is that the name used to store the series in the underlying database is still the metric name, which means that if we follow the convention of breaking the series name up by `.` and creating a subdirectory for each segment, meaning that many database files will end up in the same directory and potentially cause performance issues (depending on the filesystem in use). One potential solution to this problem would be to stored "tagged" series in a separate filesystem hierarchy using a directory structure based on a prefix of a hash of the full tagged series name.

### CODE REVIEW

**Comment by DanCech** [comment]
The latest commits here and in https://github.com/DanCech/graphite-web/pull/1 modify the way that tagged series are stored in whisper, instead of being under the "regular" filesystem hierarchy they are stored in a set of directories under `whisper/_tagged`, where the top-level folders are based on the first 3 hex digits of the sha256 hash of the tagged metric path (4096 possible folders), and the second-level folders are based on the following 3 hex digits (another 4096 possible folders) for a total of 4096^2 possible folders.  The whisper files themselves are created with any `.` in the metric path replaced with `-`, to avoid any issues where metrics, tags or values containing a '.' would end up creating further subfolders.

A concrete example:

`some.metric;tag1=value2;tag2=value.2`

with sha256 hash `effaae5b55950b150a7493d2f5430772ca2460bf7cccb4d9e523643df54c010f` would be stored in:

`_tagged/eff/aae/some-metric;tag1=value2;tag2=value-2.wsp`

**Comment by DanCech** [comment]
^ allows the tagging http calls to run by avoiding `time.sleep`, there is still a sleep in `TokenBucket` that does need to be dealt with.

**Comment by deniszh** [comment]
I generally much 👍 whole idea - tags are must have for modern metrics system.
Metric format is fine IMO - it's compatible with current tooling (contrary to metrics 2.0) and flexible enough. 
Storing problem is also fixed now. BTW, how tagged metrics will be visible to search queries / web-interface? Like `_tagged.xxx.yyy.some-metric;tag1=value2;tag2=value-2` ?
Ah, and another thing - now it's not possible to disable tag functionality and just treat ';' as a normal character? I think we need to implement such mechanism
But in general I'm very like an idea - let's merge it to master and will start to polish the whole implementation.

**Comment by DanCech** [comment]
Right now ; isn't a legal series character in graphite-web, so don't think we need to worry about anyone using it already.

Yes currently the series would show up that way, unless we hide them or add special handling in the finders.

I'm definitely a ways away from merging anything to master, but once it gets a little more tidied up I'll push to branches in the graphite-project repos.

**Comment by obfuscurity** [comment]
I'm very much in favor of this feature and the related PR for graphite-web, but I have serious concerns about encoding tags into the Whisper path. I've been anxious to see this sort of feature in Graphite for years, but I always (hand-wavily) expected the backend support to appear in a newer storage engine that could support tag storage natively. AIUI (without actually reading the code logic), any _unique_ combination of tags (excluding the same set of tags in a different order, since I assume we're at least normalizing the set) will result in a new Whisper file. This would result in a significant increase in the number of files/inodes used per Carbon/Whisper node, a highly inefficient approach imho.

Of course it's entirely possible that I'm being stupid and this isn't how you're approaching the problem at all; am I way off-base here?

**Comment by DanCech** [comment]
So the way that tags work in this scenario is that a given series/node is uniquely identified by a set of tags (after normalizing the order they occur in), and thus needs a separate whisper file on disk.  Tags are not intended to be used to store information about a given logical series that might change over time.

**Comment by obfuscurity** [comment]
I might be overblowing the impact of this design. All other "metadata" for a metric is already encoded in its Whisper namespace, so there's nothing revolutionary in that regard. What happens if someone changes the tag(s) for an existing metric? Presumably it creates a new metric; as long as we can efficiently coalesce both series together (which we already do) it shouldn't be an issue.

Does that sound about right?

**Comment by DanCech** [comment]
Yup, if you change a tag then it's a new series in the same way as if you were to change a node in a "normal" series' name.  If you make a query that matches both the "old" and "new" series then you'll get them both returned, with each one covering the relevant interval.

**Comment by obfuscurity** [comment]
WFM

**Comment by deniszh** [comment]
I'm totally agreed with @obfuscurity here - it will be nice to have tag support in a storage system. But it's better to have that (or start with that) - then have nothing. IMO this implementation features and limitations are quite OK, please proceed - much appreciated!

**Comment by DanCech** [comment]
Yeah, one of the things I have done is to leave the mapping of tagged series to filesystem path up to the finder/reader so it can be implemented differently by alternative backend storage modules.

**Pull request closed without merging**
